services:
  backend:
    image: saji7x/technews-backend:latest
    container_name: technews_backend
    restart: always
    env_file: ./backend.env
    environment:
      DB_PATH: data/news.db
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - db_data:/app/data
    networks:
      - technews

  frontend:
    image: saji7x/technews-frontend:latest
    container_name: technews_frontend
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - technews

volumes:
  db_data:
    driver: local

networks:
  technews:
    driver: bridge
