"""
SSE (Server-Sent Events) route.

GET /events?client_id=<uuid>

Opens a per-client SSE stream.  The client must supply a
``client_id`` query parameter (generated by the browser via
``crypto.randomUUID()``).  All other endpoints publish events onto
this stream using ``sse_manager``.
"""

import logging

from fastapi import APIRouter, Request
from sse_starlette.sse import EventSourceResponse

from app.exceptions.errors import InputValidationError
from app.services.sse_manager import sse_manager

logger = logging.getLogger(__name__)

router = APIRouter(tags=["sse"])


@router.get("/events")
async def events(request: Request, client_id: str) -> EventSourceResponse:
    """
    Open a Server-Sent Events stream for ``client_id``.

    The response is a long-lived HTTP connection; the server pushes named
    events (``status``, ``provider_started``, ``provider_done``,
    ``provider_error``, ``job_done``, ``result``) as news jobs progress.
    """
    if not client_id or not client_id.strip():
        raise InputValidationError("client_id query parameter is required.", field="client_id")

    queue = await sse_manager.register(client_id)
    logger.debug("SSE stream opened for client_id=%s", client_id)

    async def generate():
        try:
            while True:
                if await request.is_disconnected():
                    logger.debug("SSE client disconnected: %s", client_id)
                    break
                msg = await queue.get()
                yield msg
        finally:
            await sse_manager.unregister(client_id)
            logger.debug("SSE stream closed for client_id=%s", client_id)

    return EventSourceResponse(generate())
